In [36]:
import pandas as pd
import numpy as np

In [37]:
ratings_df = pd.read_csv('data/ratings.csv')
ratings_df.info()
ratings_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [38]:
movies_df = pd.read_csv('data/movies.csv')
movies_df.info()
movies_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [39]:
tags_df = pd.read_csv('data/tags.csv')
tags_df.info()
tags_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userId     3683 non-null   int64
 1   movieId    3683 non-null   int64
 2   tag        3683 non-null   object
 3   timestamp  3683 non-null   int64
dtypes: int64(3), object(1)
memory usage: 115.2+ KB

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [40]:
links_df = pd.read_csv('data/links.csv')
links_df.info()
links_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   imdbId   9742 non-null   int64
 2   tmdbId   9734 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 228.5 KB

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [41]:
print("Ratings duplicate:", ratings_df.duplicated().sum())

print("Tags duplicate:", tags_df.duplicated().sum())

print("Movies duplicate:", movies_df.duplicated().sum())

Ratings duplicate: 0
Tags duplicate: 0
Movies duplicate: 0

In [42]:
# Xử lý DL cho SVD
# Đọc dữ liệu ratings, dùng copy không pandas sẽ sinh ra cái gì đó? 
ratings_svd = ratings_df[
    [
        "userId",
        "movieId",
        "rating"
    ]
].copy()
ratings_svd.info()
ratings_svd.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   userId   100836 non-null  int64
 1   movieId  100836 non-null  int64
 2   rating   100836 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 2.3 MB

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [43]:
# kiểm tra xem có bị ngoài khoảng (0.5 - 5)?
ratings_svd["rating"].describe()

count    100836.000000
mean          3.501557
std           1.042529
min           0.500000
25%           3.000000
50%           3.500000
75%           4.000000
max           5.000000
Name: rating, dtype: float64

In [44]:
# kiểm tra số lượng User
ratings_svd["userId"].nunique()

610

In [45]:
ratings_svd["movieId"].nunique()

9724

In [46]:
# Tạo cột year từ title
movies_df["year"] = movies_df["title"].str.extract(r"\((\d{4})\)")

In [47]:
# Chuyển về số, lỗi sẽ thành NaN
movies_df["year"] = pd.to_numeric(
    movies_df["year"],
    errors="coerce"
)
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995.0
2,3,Grumpier Old Men (1995),Comedy|Romance,1995.0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995.0
4,5,Father of the Bride Part II (1995),Comedy,1995.0

In [48]:
# Xóa năm khỏi title
movies_df["title"] = movies_df["title"].str.replace(
    r"\(\d{4}\)",
    "",
    regex=True
).str.strip()
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995.0
1,2,Jumanji,Adventure|Children|Fantasy,1995.0
2,3,Grumpier Old Men,Comedy|Romance,1995.0
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995.0
4,5,Father of the Bride Part II,Comedy,1995.0

In [49]:
# Tính sparsity để xem độ thưa là bao nhiêu, và nêu lý do chọn SVD và SVD sẽ xử lý tốt dữ liệu thưa (không bắt buộc, chỉ tính để biết nó thưa và SVD làm tốt với DL thưa)
n_users = ratings_svd["userId"].nunique()
n_movies = ratings_svd["movieId"].nunique()
n_ratings = len(ratings_svd)

sparsity = (
    1 - n_ratings / (n_users * n_movies)
) * 100

print(f"Sparsity: {sparsity:.2f}%")

Sparsity: 98.30%

In [50]:
# Xử lý DL cho NPL
# vì ở trên đã kiểm tra và thấy bảng movies không có dữ liệu null, nhưng lại có phim không được gán nhãn nhưng vẫn có giá trị (no genres listed) - không có ý nghĩa
movies_df["genres"].unique()

array(['Adventure|Animation|Children|Comedy|Fantasy',
       'Adventure|Children|Fantasy', 'Comedy|Romance',
       'Comedy|Drama|Romance', 'Comedy', 'Action|Crime|Thriller',
       'Adventure|Children', 'Action', 'Action|Adventure|Thriller',
       'Comedy|Horror', 'Adventure|Animation|Children', 'Drama',
       'Action|Adventure|Romance', 'Crime|Drama', 'Drama|Romance',
       'Action|Comedy|Crime|Drama|Thriller', 'Comedy|Crime|Thriller',
       'Crime|Drama|Horror|Mystery|Thriller', 'Drama|Sci-Fi',
       'Children|Drama', 'Adventure|Drama|Fantasy|Mystery|Sci-Fi',
       'Mystery|Sci-Fi|Thriller', 'Children|Comedy', 'Drama|War',
       'Action|Crime|Drama', 'Action|Adventure|Fantasy',
       'Comedy|Drama|Thriller', 'Mystery|Thriller',
       'Animation|Children|Drama|Musical|Romance',
       'Crime|Mystery|Thriller', 'Adventure|Drama', 'Drama|Thriller',
       'Comedy|Crime', 'Action|Sci-Fi|Thriller',
       'Action|Comedy|Horror|Thriller', 'Comedy|Drama', 'Documentary',
       'Action|Crime|Drama|Thriller', 'Crime|Drama|Romance',
       'Action|Adventure|Drama', 'Action|Thriller',
       'Drama|Horror|Thriller', 'Comedy|Horror|Romance',
       'Adventure|Comedy|Crime|Romance',
       'Adventure|Children|Comedy|Musical', 'Action|Drama|War',
       'Crime|Drama|Thriller', 'Action|Adventure|Comedy|Crime',
       'Drama|Mystery', 'Drama|Mystery|Romance', 'Thriller',
       'Adventure|Drama|IMAX', 'Action|Drama|Romance|War', 'Drama|Horror',
       'Adventure|Drama|War', 'Comedy|War', 'Crime|Drama|Mystery',
       'Action|Adventure|Mystery|Sci-Fi', 'Drama|Thriller|War',
       'Action|Romance|Western', 'Crime|Film-Noir|Mystery|Thriller',
       'Comedy|Crime|Drama', 'Action|Drama|Romance',
       'Adventure|Children|Drama', 'Action|Adventure|Crime|Thriller',
       'Action|Crime|Sci-Fi', 'Horror', 'Action|Children',
       'Comedy|Horror|Thriller', 'Fantasy|Horror|Mystery',
       'Comedy|Fantasy', 'Horror|Sci-Fi',
       'Action|Crime|Drama|Mystery|Sci-Fi|Thriller',
       'Drama|Musical|Romance', 'Drama|Fantasy',
       'Action|Adventure|Sci-Fi', 'Western',
       'Adventure|Comedy|Crime|Mystery', 'Adventure|Comedy',
       'Action|Comedy|Romance', 'Animation|Children|Comedy|Romance',
       'Drama|Musical', 'Children|Comedy|Fantasy', 'Comedy|Sci-Fi',
       'Adventure|Children|Comedy|Fantasy|Romance',
       'Drama|Fantasy|Romance', 'Drama|Romance|War|Western',
       'Drama|Horror|Sci-Fi', 'Action|Crime',
       'Action|Drama|Sci-Fi|Thriller', 'Comedy|Crime|Drama|Thriller',
       'Action|Thriller|Western', 'Horror|Thriller', 'Animation|Children',
       'Children|Drama|Fantasy|Mystery', 'Action|Drama|Thriller',
       'Comedy|Drama|Fantasy', 'Film-Noir|Thriller',
       'Action|Comedy|Sci-Fi', 'Adventure|Drama|Sci-Fi',
       'Action|Crime|Horror', 'Children', 'Drama|Film-Noir|Romance',
       'Drama|Mystery|Thriller', 'Action|Crime|Fantasy|Thriller',
       'Comedy|Drama|Romance|War', 'Action|Comedy',
       'Adventure|Children|Romance',
       'Adventure|Animation|Children|Drama|Musical|IMAX',
       'Drama|Horror|Mystery|Thriller', 'Action|Comedy|Crime|Fantasy',
       'Adventure|Comedy|Western', 'Action|Romance|Thriller',
       'Action|Adventure|Comedy|Romance|Thriller',
       'Drama|Horror|Romance|Thriller', 'Drama|Romance|War',
       'Action|Fantasy', 'Comedy|Thriller',
       'Action|Comedy|Crime|Thriller', 'Horror|Sci-Fi|Thriller',
       'Drama|Mystery|Romance|Thriller', 'Action|Comedy|Drama',
       'Drama|Western', 'Action|Adventure|Crime|Drama|Romance|Thriller',
       'Action|Comedy|War', 'Action|Adventure|Sci-Fi|Thriller',
       'Action|Adventure|Comedy|Fantasy', 'Comedy|Western',
       'Comedy|Mystery', 'Comedy|Drama|Romance|Thriller',
       'Action|Children|Romance', 'Action|Drama|Sci-Fi', 'Action|Drama',
       'Comedy|Mystery|Romance', 'Action|Drama|Mystery',
       'Action|Crime|Drama|Sci-Fi|Thriller', 'Crime|Thriller',
       'Comedy|Crime|Horror', 'Action|Adventure|Fantasy|Mystery',
       'Comedy|Romance|Thriller',
       'Action|Adventure|Children|Comedy|Fantasy|Sci-Fi',
       'Action|Mystery|Thriller', 'Animation|Children|Fantasy|Musical',
       'Action|Adventure|Comedy|Romance', 'Action|Drama|Western',
       'Action|Adventure|Animation|Children|Fantasy',
       'Comedy|Drama|Fantasy|Romance|Thriller',
       'Adventure|Animation|Children|Comedy|Musical', 'Action|Sci-Fi',
       'Adventure|Drama|Western', 'Crime|Horror|Thriller',
       'Animation|Children|Drama|Fantasy|Musical',
       'Animation|Children|Fantasy|Musical|Romance|IMAX',
       'Adventure|Western', 'Action|Comedy|Crime', 'Fantasy|Horror',
       'Action|Adventure|Animation|Horror|Sci-Fi', 'Action|Horror|Sci-Fi',
       'Crime|Drama|Mystery|Thriller',
       'Adventure|Animation|Children|Fantasy|Musical|Romance', 'Romance',
       'Action|Crime|Drama|War', 'Action|Adventure|Mystery|Thriller',
       'Adventure|Animation|Children|Fantasy|Musical', 'Comedy|Drama|War',
       'Adventure|Animation|Children|Comedy|Fantasy|Sci-Fi',
       'Adventure|Comedy|Sci-Fi', 'Drama|Mystery|Romance|Sci-Fi|Thriller',
       'Action|Adventure|Comedy|War', 'Action|Adventure',
       'Drama|Mystery|Western', 'Comedy|Fantasy|Sci-Fi',
       'Adventure|Animation|Comedy', 'Drama|Fantasy|Horror|Thriller',
       'Action|Adventure|Romance|Thriller', 'Animation|Sci-Fi',
       'Animation|Children|Comedy', 'Horror|Mystery',
       'Comedy|Fantasy|Romance|Sci-Fi', 'Action|Adventure|Drama|Thriller',
       'Comedy|Fantasy|Musical', 'Crime|Drama|Romance|Thriller',
       'Crime|Drama|Musical|Thriller', 'Sci-Fi|Thriller',
       'Children|Drama|Fantasy', 'Adventure|Animation|Children|Musical',
       'Adventure|Drama|Romance|War', 'Comedy|Musical|Romance',
       'Musical|Romance', 'Comedy|Musical',
       'Action|Adventure|Mystery|Romance|Thriller',
       'Comedy|Crime|Mystery|Romance|Thriller', 'Film-Noir|Mystery',
       'Comedy|Drama|Musical|Romance', 'Musical',
       'Adventure|Children|Fantasy|Musical',
       'Drama|Film-Noir|Mystery|Thriller', 'Film-Noir|Romance|Thriller',
       'Mystery|Romance|Thriller', 'Crime|Mystery|Romance|Thriller',
       'Adventure', 'Crime|Film-Noir|Mystery', 'Drama|Romance|Western',
       'Children|Drama|Fantasy|Romance', 'Adventure|Comedy|Romance|War',
       'Adventure|Comedy|Crime|Drama|Romance', 'Romance|War',
       'Crime|Film-Noir', 'Children|Comedy|Western',
       'Children|Comedy|Fantasy|Romance', 'Children|Comedy|Romance',
       'Children|Comedy|Drama', 'Children|Comedy|Mystery',
       'Animation|Children|Fantasy|Musical|Romance',
       'Animation|Children|Musical', 'Children|Comedy|Fantasy|Musical',
       'Animation|Children|Drama|Musical', 'Adventure|Children|Musical',
       'Animation|Children|Drama', 'Action|Horror|Sci-Fi|Thriller',
       'Documentary|Drama',
       'Animation|Children|Comedy|Fantasy|Musical|Romance',
       'Drama|Romance|Thriller', 'Children|Drama|Sci-Fi',
       'Action|Romance', 'Adventure|Comedy|Fantasy',
       'Animation|Children|Comedy|Crime',
       'Animation|Comedy|Drama|Fantasy', 'Crime|Drama|Film-Noir',
       'Documentary|Musical', 'Action|Adventure|Comedy|Fantasy|Romance',
       'Fantasy|Sci-Fi', 'Action|Adventure|Horror|Sci-Fi',
       'Action|Adventure|Western', 'Crime|Drama|Sci-Fi|Thriller',
       'Film-Noir|Mystery|Thriller',
       'Action|Adventure|Comedy|Fantasy|Horror',
       'Adventure|Drama|Romance', 'Crime|Horror', 'Action|Comedy|Musical',
       'Adventure|Animation|Children|Comedy|Sci-Fi',
       'Drama|Mystery|Sci-Fi', 'Comedy|Fantasy|Horror',
       'Crime|Drama|Film-Noir|Thriller', 'Crime|Film-Noir|Thriller',
       'Action|Crime|Romance|Thriller', 'Drama|Sci-Fi|Thriller',
       'Action|Adventure|Drama|Western', 'Comedy|Horror|Sci-Fi',
       'Comedy|Musical|War', 'Action|Comedy|Fantasy|Horror',
       'Action|Adventure|Drama|War',
       'Action|Drama|Mystery|Romance|Thriller', 'Comedy|Fantasy|Romance',
       'Crime|Thriller|War', 'Comedy|Mystery|Thriller',
       'Comedy|Drama|Film-Noir', 'Action|Adventure|Animation|Sci-Fi',
       'Action|Western', 'Fantasy|Horror|Romance|Thriller',
       'Drama|Fantasy|Horror', 'Horror|Mystery|Thriller',
       'Adventure|Children|Comedy', 'Adventure|Sci-Fi',
       'Action|Mystery|Sci-Fi', 'Action|Comedy|Western', 'Action|Horror',
       'Action|Comedy|Crime|Drama|Sci-Fi',
       'Adventure|Animation|Comedy|Crime',
       'Comedy|Horror|Mystery|Thriller', 'Action|Romance|War|Western',
       'Comedy|Drama|Fantasy|Romance', 'Action|Adventure|Comedy|Thriller',
       'Crime', 'Crime|Drama|Fantasy|Film-Noir|Mystery|Romance',
       'Action|Comedy|Crime|Drama', 'Action|Romance|Sci-Fi|Thriller',
       'Comedy|Drama|Mystery|Romance', 'Action|Adventure|Children',
       'Comedy|Crime|Romance', 'Action|Adventure|Comedy',
       'Action|Adventure|Comedy|Sci-Fi',
       'Action|Adventure|Fantasy|Thriller', 'Children|Fantasy',
       'Adventure|Romance', 'Action|Thriller|War',
       'Children|Comedy|Romance|Sci-Fi', 'Romance|Thriller',
       'Comedy|Drama|Sci-Fi',
       'Adventure|Animation|Children|Drama|Musical',
       'Action|Adventure|Drama|Sci-Fi', 'Action|Children|Comedy',
       'Adventure|Film-Noir|Sci-Fi|Thriller',
       'Crime|Drama|Fantasy|Thriller', 'Crime|Romance|Thriller',
       'Crime|Drama|Mystery|Romance|Thriller', 'Documentary|IMAX',
       'Comedy|Crime|Drama|Mystery|Thriller', 'Comedy|Documentary',
       'Adventure|Children|Comedy|Fantasy', 'Crime|Drama|Romance|War',
       'Adventure|Comedy|Drama', 'Adventure|Comedy|Romance',
       'Adventure|Animation|Children|Comedy|Drama|Musical|Romance',
       'Action|Crime|Mystery|Sci-Fi|Thriller',
       'Comedy|Crime|Drama|Romance|Thriller',
       'Animation|Children|Fantasy|War', 'Comedy|Drama|Musical',
       'Adventure|Fantasy|Musical',
       'Action|Adventure|Children|Comedy|Fantasy',
       'Drama|Mystery|Sci-Fi|Thriller', 'Adventure|Comedy|Sci-Fi|Western',
       'Children|Fantasy|Musical', 'Adventure|Animation|Children|Fantasy',
       'Children|Sci-Fi', 'Children|Comedy|Sci-Fi',
       'Action|Adventure|Children|Comedy', 'Adventure|Children|Sci-Fi',
       'Action|Animation|Children|Crime',
       'Children|Comedy|Fantasy|Horror',
       'Adventure|Children|Comedy|Fantasy|Sci-Fi',
       'Action|Crime|Drama|Mystery|Thriller', 'Film-Noir',
       'Drama|Fantasy|Mystery', 'Animation|Children|Comedy|Musical',
       'Animation|Children|Comedy|Musical|Romance',
       'Children|Comedy|Musical', 'Children|Musical',
       'Adventure|Comedy|Musical',
       'Adventure|Animation|Children|Crime|Drama',
       'Children|Drama|Fantasy|Mystery|Thriller',
       'Adventure|Children|Fantasy|Western',
       'Animation|Children|Comedy|Drama|Fantasy',
       'Action|Crime|Mystery|Thriller',
       'Adventure|Animation|Children|Drama|Fantasy',
       'Adventure|Animation|Children|Drama', 'Adventure|Fantasy',
       'Adventure|Animation|Children|Comedy',
       'Adventure|Animation|Children|Musical|Western',
       'Adventure|Fantasy|Romance', 'Adventure|Drama|Fantasy',
       'Action|Comedy|Drama|Horror', 'Action|Horror|Thriller',
       'Drama|Film-Noir|Thriller', 'Adventure|Drama|Mystery|Thriller',
       'Horror|Mystery|Sci-Fi|Thriller', 'Drama|Fantasy|Thriller',
       'Adventure|Drama|Fantasy|Romance', 'Sci-Fi',
       'Drama|Fantasy|Mystery|Romance', 'Action|Sci-Fi|War',
       'Fantasy|Horror|Thriller', 'Horror|Western',
       'Action|Adventure|Fantasy|Horror',
       'Adventure|Fantasy|Romance|Sci-Fi|Thriller',
       'Comedy|Crime|Mystery', 'Action|Drama|Romance|Sci-Fi',
       'Animation|Musical', 'Action|Adventure|Thriller|War',
       'Comedy|Crime|Mystery|Thriller',
       'Action|Adventure|Children|Fantasy|Mystery|Thriller',
       'Action|Adventure|Children|Drama',
       'Action|Adventure|Drama|Fantasy|Thriller', 'Horror|Mystery|Sci-Fi',
       'Drama|Horror|Sci-Fi|Thriller', 'Action|Comedy|Romance|Thriller',
       'Action|War', 'Adventure|Comedy|Thriller',
       'Action|Sci-Fi|Thriller|Western', 'Drama|Romance|Sci-Fi|Thriller',
       'Drama|Film-Noir',
       'Action|Adventure|Comedy|Fantasy|Horror|Thriller',
       'Action|Adventure|Crime|Sci-Fi|Thriller',
       'Adventure|Drama|Mystery', 'Horror|Romance',
       'Comedy|Horror|Musical|Sci-Fi', 'War', 'Comedy|Romance|Sci-Fi',
       'Animation|Comedy|Musical', 'Action|Comedy|Sci-Fi|Western',
       'Action|Comedy|Fantasy', 'Adventure|Drama|Thriller',
       'Action|Adventure|Comedy|Fantasy|Mystery', 'Comedy|Horror|Musical',
       'Adventure|Animation|Children|Drama|Sci-Fi',
       'Drama|Horror|Mystery', 'Action|Mystery',
       'Comedy|Horror|Romance|Thriller', 'Action|Drama|Romance|Thriller',
       'Animation|Horror|Mystery|Thriller',
       'Adventure|Children|Comedy|Drama', 'Adventure|Sci-Fi|Thriller',
       'Adventure|Animation|Comedy|Fantasy|Musical',
       'Animation|Children|Fantasy', 'Action|Adventure|Comedy|Drama|War',
       'Crime|Drama|Western', 'Comedy|Crime|Drama|Fantasy',
       'Drama|Film-Noir|Mystery|Romance', 'Musical|Romance|War',
       'Adventure|Comedy|Fantasy|Sci-Fi', 'Drama|Fantasy|Musical',
       'Action|Crime|Sci-Fi|Thriller',
       'Adventure|Animation|Children|Comedy|Crime|Fantasy|Mystery',
       'Action|Adventure|Animation|Drama|Fantasy',
       'Adventure|Animation|Children|Fantasy|Sci-Fi',
       'Fantasy|Horror|Mystery|Romance',
       'Action|Fantasy|Horror|Mystery|Thriller', 'Drama|Romance|Sci-Fi',
       'Animation|Children|Musical|IMAX', 'Action|Comedy|Horror',
       'Action|Crime|Thriller|Western', 'Fantasy|Horror|Mystery|Thriller',
       'Romance|Western', 'Adventure|Crime|Drama|Romance',
       'Adventure|Crime|Drama', 'Animation|Comedy',
       'Action|Children|Comedy|Fantasy|Sci-Fi', 'Action|Children|Fantasy',
       'Action|Adventure|Drama|Thriller|Western',
       'Crime|Horror|Mystery|Thriller', 'Action|Adventure|Comedy|Western',
       'Action|Drama|Thriller|Western',
       'Adventure|Animation|Fantasy|Sci-Fi',
       'Comedy|Horror|Sci-Fi|Thriller', 'Adventure|Drama|Romance|Sci-Fi',
       'Film-Noir|Horror|Mystery|Thriller',
       'Action|Adventure|Animation|Children|Sci-Fi',
       'Action|Fantasy|Horror|Sci-Fi|Thriller',
       'Action|Comedy|Crime|Romance', 'Adventure|Horror|Sci-Fi',
       'Adventure|Animation|Children|Sci-Fi', 'Adventure|Comedy|Crime',
       'Action|Drama|War|Western',
       'Action|Crime|Mystery|Romance|Thriller', 'Romance|Sci-Fi',
       'Fantasy|Romance', 'Action|Adventure|Fantasy|Sci-Fi',
       'Adventure|Comedy|Horror', 'Animation|Comedy|Fantasy',
       'Action|Adventure|War', 'Action|Crime|Drama|Horror|Thriller',
       'Crime|Mystery', 'Adventure|Comedy|Mystery|Romance',
       'Adventure|Animation|Children|Comedy|Fantasy|Romance',
       'Adventure|War|Western', 'Comedy|Drama|Mystery|Thriller',
       'Comedy|Drama|Romance|Western', 'Action|Comedy|Sci-Fi|Thriller',
       'Adventure|Documentary|IMAX', 'Animation|Drama|Sci-Fi|IMAX',
       'Action|Comedy|Horror|Sci-Fi', 'Comedy|Musical|Sci-Fi',
       'Drama|Musical|Mystery', 'Crime|Musical', 'Comedy|Musical|Western',
       'Action|Animation|Comedy|Crime|Drama|Romance|Thriller',
       'Action|Adventure|Drama|Romance',
       'Comedy|Fantasy|Horror|Musical|Thriller', 'Crime|Horror|Mystery',
       'Action|Adventure|Drama|Romance|Thriller',
       'Action|Comedy|Romance|War', 'Action|Adventure|Comedy|Drama',
       'Adventure|Thriller', 'Crime|Drama|Film-Noir|Mystery|Thriller',
       'Action|Animation|Sci-Fi', 'Animation|Drama|Fantasy',
       'Drama|Fantasy|Mystery|Sci-Fi',
       'Drama|Fantasy|Horror|Thriller|War', 'Fantasy|Mystery|Thriller',
       'Action|Adventure|Comedy|Drama|Romance|Thriller',
       'Mystery|Romance|Sci-Fi|Thriller',
       'Adventure|Crime|Drama|Thriller', 'Comedy|Drama|Mystery',
       'Animation|Fantasy', 'Drama|Fantasy|Horror|Mystery|Thriller',
       'Drama|Fantasy|Mystery|Romance|Thriller',
       'Animation|Fantasy|Horror|Sci-Fi', 'Documentary|War',
       'Children|Horror|Mystery|Thriller', 'Musical|Western',
       'Action|Adventure|Sci-Fi|IMAX',
       'Adventure|Animation|Children|Western',
       'Adventure|Children|Comedy|Fantasy|Mystery',
       'Adventure|Drama|Horror|Mystery|Thriller',
       'Comedy|Sci-Fi|Thriller', 'Action|Animation|Children|Comedy',
       'Children|Drama|Musical', 'Comedy|Drama|Fantasy|Sci-Fi',
       'Action|Adventure|Fantasy|Romance',
       'Comedy|Crime|Romance|Thriller', 'Adventure|War',
       'Comedy|Crime|Musical|Mystery', 'Adventure|Animation|Fantasy',
       'Animation|Comedy|War', 'Action|Adventure|Comedy|Crime|Drama',
       'Animation|Drama|War', 'Documentary|Horror',
       'Action|Horror|Mystery|Sci-Fi', 'Action|Comedy|Documentary',
       'Adventure|Animation|Children|Sci-Fi|IMAX', 'Comedy|Drama|Horror',
       'Animation|Children|Drama|Fantasy', 'Comedy|Crime|Drama|Musical',
       'Action|Adventure|Animation|Fantasy|Sci-Fi',
       'Action|Adventure|Crime|Drama|Thriller',
       'Comedy|Crime|Drama|Romance', 'Comedy|Documentary|Musical',
       'Action|Animation|Sci-Fi|Thriller',
       'Adventure|Children|Comedy|Mystery', 'Mystery|Sci-Fi',
       'Adventure|Children|Comedy|Fantasy|Musical',
       'Action|Adventure|Animation|Children|Fantasy|Sci-Fi',
       'Action|Adventure|Sci-Fi|Thriller|IMAX',
       'Action|Drama|Horror|Sci-Fi|Thriller', 'Drama|War|Western',
       'Comedy|Crime|Mystery|Romance', 'Comedy|War|Western',
       'Action|Adventure|Comedy|Crime|Thriller', 'Action|Fantasy|Sci-Fi',
       'Action|Comedy|Thriller', 'Comedy|Crime|Drama|War',
       'Adventure|Comedy|Crime|Thriller',
       'Action|Adventure|Children|Fantasy',
       'Drama|Fantasy|Musical|Romance', 'Animation|Drama|Romance',
       'Comedy|Romance|Sci-Fi|Thriller', 'Action|Fantasy|Horror',
       'Fantasy|Horror|Sci-Fi|Thriller', 'Comedy|Musical|Romance|Western',
       'Drama|Fantasy|Sci-Fi', 'Children|Comedy|Crime|Musical',
       'Action|Adventure|Animation|Fantasy', 'Crime|Documentary',
       'Adventure|Comedy|Drama|Fantasy|Mystery|Sci-Fi|Thriller',
       'Action|Animation|Children|Fantasy', 'Comedy|Mystery|Sci-Fi',
       'Adventure|Thriller|Western', 'Comedy|Crime|Drama|Mystery|Romance',
       'Action|Crime|Fantasy|Sci-Fi|Thriller', 'Crime|Fantasy|Horror',
       'Action|Drama|Horror|Thriller', 'Comedy|Fantasy|Horror|Thriller',
       'Action|Drama|Romance|Western',
       'Adventure|Animation|Drama|Fantasy|Sci-Fi',
       'Animation|Drama|Sci-Fi|War', 'Action|Adventure|Drama|Fantasy',
       'Adventure|Drama|Romance|Thriller|War',
       'Crime|Drama|Film-Noir|Romance|Thriller',
       'Drama|Film-Noir|Mystery',
       'Action|Comedy|Crime|Drama|Horror|Thriller',
       'Adventure|Documentary', 'Action|Adventure|Children|Comedy|Crime',
       'Animation|Comedy|Fantasy|Musical',
       'Action|Adventure|Children|Comedy|Mystery', 'Action|Drama|Horror',
       'Musical|Romance|Western', 'Action|Drama|Thriller|War',
       'Comedy|Crime|Drama|Musical|Mystery|Romance',
       'Adventure|Comedy|War', 'Fantasy|Musical|Romance',
       'Drama|Thriller|Western', 'Crime|Horror|Sci-Fi',
       'Animation|Fantasy|Thriller', 'Children|Comedy|Fantasy|Sci-Fi',
       'Mystery', 'Action|Adventure|Animation|Comedy|Crime|Mystery',
       'Adventure|Animation|Children|Comedy|Musical|Romance',
       'Action|Adventure|Drama|Sci-Fi|Thriller', 'Adventure|Fantasy|IMAX',
       'Action|Crime|Horror|Mystery|Thriller', 'Comedy|Fantasy|Thriller',
       'Animation|Comedy|Drama|Fantasy|Sci-Fi',
       'Comedy|Documentary|Drama', 'Crime|Drama|Film-Noir|Romance',
       'Action|Adventure|Drama|Romance|Thriller|Western',
       'Crime|Drama|Horror', 'Adventure|Comedy|Fantasy|Musical',
       'Adventure|Animation|Drama', 'Comedy|Drama|Fantasy|Mystery',
       'Action|Crime|Fantasy', 'Comedy|Drama|Sci-Fi|War',
       'Adventure|Fantasy|Sci-Fi',
       'Adventure|Drama|Horror|Sci-Fi|Thriller',
       'Action|Adventure|Animation|Comedy',

In [51]:
# Đếm có bao nhiêu phim không được gán nhãn, được gán giá trị (no genres listed)
count = len(
    movies_df[movies_df["genres"] == "(no genres listed)"]
)
print(count)

34

In [52]:
# Thay (no genres listed) thành ""
movies_df["genres"] = movies_df["genres"].replace(
    "(no genres listed)",
    ""
)

In [53]:
# Kiểm tra lại đã thay chưa
count = len(
    movies_df[movies_df["genres"] == "(no genres listed)"]
)
print(count)

0

In [54]:
# Thay dấu | trong genres bằng khoảng trắng
movies_df["genres"] = movies_df["genres"].str.replace(
    "|",
    " ",
    regex=False
)
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0
1,2,Jumanji,Adventure Children Fantasy,1995.0
2,3,Grumpier Old Men,Comedy Romance,1995.0
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0
4,5,Father of the Bride Part II,Comedy,1995.0

In [56]:
# Xử lý tags
# Chuẩn hóa thành chữ thường 
tags_df["tag"] = tags_df["tag"].str.lower()
tags_df.head()

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     boxing story  1445715207
4       2    89774              mma  1445715200

In [57]:
# Loại bỏ khoảng trắng thừa, ở 2 đầu nếu người dùng lỡ bấm space trước/sau khi viết 
tags_df["tag"] = tags_df["tag"].str.strip()
tags_df.head()

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     boxing story  1445715207
4       2    89774              mma  1445715200

In [58]:
# Gom tag theo movie
movie_tags = tags_df.groupby("movieId")["tag"].apply(" ".join).reset_index()
movie_tags.head()

   movieId                                           tag
0        1                               pixar pixar fun
1        2  fantasy magic board game robin williams game
2        3                                     moldy old
3        5                              pregnancy remake
4        7                                        remake

In [59]:
# Xử lý trùng lặp tag, ví dụ (pixar pixar fun)
movie_tags["tag"] = movie_tags["tag"].apply(
    lambda x: " ".join(
        dict.fromkeys(x.split())
    )
)
movie_tags.head()

   movieId                                      tag
0        1                                pixar fun
1        2  fantasy magic board game robin williams
2        3                                moldy old
3        5                         pregnancy remake
4        7                                   remake

In [60]:
# Ghép tag vào movies
movies_nlp = movies_df.merge(
    movie_tags,
    on="movieId",
    how="left"
)
movies_nlp.head()

,movieId,title,genres,year,tag
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar fun
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,NaN
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake

In [61]:
# Xử lý Null
movies_nlp["tag"] = (
    movies_nlp["tag"]
    .fillna("")
)
movies_nlp.head()

,movieId,title,genres,year,tag
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar fun
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake

In [62]:
# Ghép title, genres, tag thành 1 cột content 
movies_nlp["content"] = (
    movies_nlp["title"]
    + " "
    + movies_nlp["genres"]
    + " "
    + movies_nlp["tag"]
)
movies_nlp.head()

,movieId,title,genres,year,tag,content
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar fun,Toy Story Adventure Animation Children Comedy ...
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams,Jumanji Adventure Children Fantasy fantasy mag...
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old,Grumpier Old Men Comedy Romance moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,,Waiting to Exhale Comedy Drama Romance
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake,Father of the Bride Part II Comedy pregnancy r...

In [63]:
# Chuyển về chữ thường 
movies_nlp["content"] = (
    movies_nlp["content"]
    .str.lower()
)
movies_nlp.head()

,movieId,title,genres,year,tag,content
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar fun,toy story adventure animation children comedy ...
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams,jumanji adventure children fantasy fantasy mag...
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old,grumpier old men comedy romance moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,,waiting to exhale comedy drama romance
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake,father of the bride part ii comedy pregnancy r...

In [67]:
# Đếm số ký tự đặc biệt trong content 
special_content = movies_nlp[
    movies_nlp["content"].str.contains(
        r"[^a-zA-Z0-9\s]",
        regex=True,
        na=False
    )
]

print(len(special_content))

0

In [72]:
# Loại bỏ ký tự đặc biệt, chỉ giữ lại chữ cái, số và khoảng trắng
movies_nlp["content"] = (
    movies_nlp["content"]
    .str.replace(
        r"[^a-zA-Z0-9\s]",
        " ",
        regex=True
    )
)
movies_nlp.head()

,movieId,title,genres,year,tag,content
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar fun,toy story adventure animation children comedy ...
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams,jumanji adventure children fantasy fantasy mag...
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old,grumpier old men comedy romance moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,,waiting to exhale comedy drama romance
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake,father of the bride part ii comedy pregnancy r...

In [73]:
# Loại bỏ khoảng trắng thừa, ở giữa nếu có nhiều khoảng trắng sẽ thành 1 khoảng trắng, ở 2 đầu nếu có sẽ bị xóa
movies_nlp["content"] = (
    movies_nlp["content"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)
movies_nlp.head()

,movieId,title,genres,year,tag,content
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar fun,toy story adventure animation children comedy ...
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams,jumanji adventure children fantasy fantasy mag...
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old,grumpier old men comedy romance moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,,waiting to exhale comedy drama romance
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake,father of the bride part ii comedy pregnancy r...

In [74]:
# Tính TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(
    stop_words="english"
)
tfidf_matrix = tfidf.fit_transform(
    movies_nlp["content"]
)
print(tfidf_matrix.shape)

(9742, 9801)

In [77]:
feature_names = tfidf.get_feature_names_out()

print(feature_names[:200])

['00' '000' '007' '01' '04' '06' '09' '10' '100' '1000' '101' '102' '10th'
 '11' '1138' '11th' '12' '120' '127' '13' '13th' '14' '1408' '1492' '15'
 '16' '1600' '17' '174' '1776' '18' '187' '19' '1900' '1900s' '1920s'
 '1933' '1935' '1941' '1950s' '1960s' '1969' '1970s' '1972' '1975' '1980s'
 '1984' '1985' '1990' '1990s' '1992' '1st' '20' '200' '2000' '2001' '2006'
 '2007' '2010' '2012' '2018' '2046' '2048' '2049' '21' '211' '22' '23'
 '24' '25' '250' '25th' '27' '28' '281' '2d' '2nd' '30' '300' '3000' '31'
 '33' '34th' '35' '37th' '39' '3d' '3dd' '40' '400' '42' '42nd' '43' '44'
 '45' '451' '46' '47' '48' '49' '4th' '50' '500' '51' '52' '54' '57' '571'
 '5th' '60' '61' '66' '6th' '70' '70mm' '71' '73' '77' '777' '7th' '80'
 '800' '81' '84' '8mm' '8th' '90' '900' '911' '93' '96' '964' '99' '9to5'
 'aan' 'aardman' 'aaron' 'abandoned' 'abbey' 'abbott' 'abbotts' 'abcs'
 'abduction' 'abiding' 'abominable' 'abortion' 'abracadabra' 'abraham'
 'abre' 'abroad' 'absence' 'absent' 'absentia' 'absolute' 'absolutely'
 'absorbing' 'abstract' 'abuse' 'abyss' 'academy' 'accepted' 'accident'
 'accidental' 'accidents' 'according' 'accountant' 'accused' 'ace' 'aces'
 'achronological' 'acid' 'acquaintance' 'acres' 'act' 'acting' 'action'
 'activity' 'actors' 'actress' 'actrice' 'acts' 'actually' 'ad' 'adam'
 'adams' 'adanggaman' 'adaptation' 'addams' 'addendum' 'adderall' 'addict'
 'addicted' 'addiction' 'adentro' 'adjustment' 'admirer' 'admission' 'ado'
 'adolescence' 'adoption']

In [ ]:
# Tính cosine similarity để đo độ tương đồng giữa các vector phim.
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(
    tfidf_matrix,
    tfidf_matrix
)
print(cosine_sim.shape)

(9742, 9742)

In [79]:
# Tạo Series để map index với title, dùng drop_duplicates để tránh trường hợp có phim trùng tên
indices = pd.Series(
    movies_nlp.index,
    index=movies_nlp["title"]
).drop_duplicates()
indices.head()

title
Toy Story                      0
Jumanji                        1
Grumpier Old Men               2
Waiting to Exhale              3
Father of the Bride Part II    4
dtype: int64

In [80]:
# Hàm đề xuất phim dựa trên title, trả về 10 phim tương tự nhất
def recommend_movies(title, cosine_sim=cosine_sim): 
    idx = indices[title]
    sim_scores = list(
        enumerate(cosine_sim[idx])
    )
    sim_scores = sorted(
        sim_scores,
        key=lambda x: x[1],
        reverse=True
    )
    sim_scores = sim_scores[1:11]

    movie_indices = [
        i[0] for i in sim_scores
    ]
    return movies_nlp[
        ["title","genres"]
    ].iloc[movie_indices]

In [ ]:
# Test hàm đề xuất
recommend_movies("Toy Story")

,title,genres
7355,Toy Story 3,Adventure Animation Children Comedy Fantasy IMAX
2355,Toy Story 2,Adventure Animation Children Comedy Fantasy
3595,"Toy, The",Comedy
1757,"Bug's Life, A",Adventure Animation Children Comedy
3733,Fun,Crime Drama
2539,We're Back! A Dinosaur's Story,Adventure Animation Children Fantasy
4089,Toy Soldiers,Action Drama
2227,"Story of Us, The",Comedy Drama
1617,"NeverEnding Story, The",Adventure Children Fantasy
6194,"Wild, The",Adventure Animation Children Comedy Fantasy