In [1]:
import pandas as pd
import numpy as np

In [2]:
ratings_df = pd.read_csv('data/ratings.csv')
ratings_df.info()
ratings_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [3]:
movies_df = pd.read_csv('data/movies.csv')
movies_df.info()
movies_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
tags_df = pd.read_csv('data/tags.csv')
tags_df.info()
tags_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userId     3683 non-null   int64
 1   movieId    3683 non-null   int64
 2   tag        3683 non-null   object
 3   timestamp  3683 non-null   int64
dtypes: int64(3), object(1)
memory usage: 115.2+ KB

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [5]:
links_df = pd.read_csv('data/links.csv')
links_df.info()
links_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   imdbId   9742 non-null   int64
 2   tmdbId   9734 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 228.5 KB

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [6]:
print("Ratings duplicate:", ratings_df.duplicated().sum())

print("Tags duplicate:", tags_df.duplicated().sum())

print("Movies duplicate:", movies_df.duplicated().sum())

Ratings duplicate: 0
Tags duplicate: 0
Movies duplicate: 0

In [7]:
# Xử lý DL cho SVD
# Đọc dữ liệu ratings, dùng copy không pandas sẽ sinh ra cái gì đó? 
ratings_svd = ratings_df[
    [
        "userId",
        "movieId",
        "rating"
    ]
].copy()
ratings_svd.info()
ratings_svd.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   userId   100836 non-null  int64
 1   movieId  100836 non-null  int64
 2   rating   100836 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 2.3 MB

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [8]:
# kiểm tra xem có bị ngoài khoảng (0.5 - 5)?
ratings_svd["rating"].describe()

count    100836.000000
mean          3.501557
std           1.042529
min           0.500000
25%           3.000000
50%           3.500000
75%           4.000000
max           5.000000
Name: rating, dtype: float64

In [9]:
# kiểm tra số lượng User
ratings_svd["userId"].nunique()

610

In [10]:
ratings_svd["movieId"].nunique()

9724

In [11]:
# Tạo cột year từ title
movies_df["year"] = movies_df["title"].str.extract(r"\((\d{4})\)")

In [12]:
# Chuyển về số, lỗi sẽ thành NaN
movies_df["year"] = pd.to_numeric(
    movies_df["year"],
    errors="coerce"
)
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995.0
2,3,Grumpier Old Men (1995),Comedy|Romance,1995.0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995.0
4,5,Father of the Bride Part II (1995),Comedy,1995.0

In [13]:
# Xóa năm khỏi title
movies_df["title"] = movies_df["title"].str.replace(
    r"\(\d{4}\)",
    "",
    regex=True
).str.strip()
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995.0
1,2,Jumanji,Adventure|Children|Fantasy,1995.0
2,3,Grumpier Old Men,Comedy|Romance,1995.0
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995.0
4,5,Father of the Bride Part II,Comedy,1995.0

In [14]:
# Tính sparsity để xem độ thưa là bao nhiêu, và nêu lý do chọn SVD và SVD sẽ xử lý tốt dữ liệu thưa (không bắt buộc, chỉ tính để biết nó thưa và SVD làm tốt với DL thưa)
n_users = ratings_svd["userId"].nunique()
n_movies = ratings_svd["movieId"].nunique()
n_ratings = len(ratings_svd)

sparsity = (
    1 - n_ratings / (n_users * n_movies)
) * 100

print(f"Sparsity: {sparsity:.2f}%")

Sparsity: 98.30%

In [15]:
# Xử lý DL cho NPL
# vì ở trên đã kiểm tra và thấy bảng movies không có dữ liệu null, nhưng lại có phim không được gán nhãn nhưng vẫn có giá trị (no genres listed) - không có ý nghĩa
movies_df["genres"].unique()

array(['Adventure|Animation|Children|Comedy|Fantasy',
       'Adventure|Children|Fantasy', 'Comedy|Romance',
       'Comedy|Drama|Romance', 'Comedy', 'Action|Crime|Thriller',
       'Adventure|Children', 'Action', 'Action|Adventure|Thriller',
       'Comedy|Horror', 'Adventure|Animation|Children', 'Drama',
       'Action|Adventure|Romance', 'Crime|Drama', 'Drama|Romance',
       'Action|Comedy|Crime|Drama|Thriller', 'Comedy|Crime|Thriller',
       'Crime|Drama|Horror|Mystery|Thriller', 'Drama|Sci-Fi',
       'Children|Drama', 'Adventure|Drama|Fantasy|Mystery|Sci-Fi',
       'Mystery|Sci-Fi|Thriller', 'Children|Comedy', 'Drama|War',
       'Action|Crime|Drama', 'Action|Adventure|Fantasy',
       'Comedy|Drama|Thriller', 'Mystery|Thriller',
       'Animation|Children|Drama|Musical|Romance',
       'Crime|Mystery|Thriller', 'Adventure|Drama', 'Drama|Thriller',
       'Comedy|Crime', 'Action|Sci-Fi|Thriller',
       'Action|Comedy|Horror|Thriller', 'Comedy|Drama', 'Documentary',
       'Action|Crime|Drama|Thriller', 'Crime|Drama|Romance',
       'Action|Adventure|Drama', 'Action|Thriller',
       'Drama|Horror|Thriller', 'Comedy|Horror|Romance',
       'Adventure|Comedy|Crime|Romance',
       'Adventure|Children|Comedy|Musical', 'Action|Drama|War',
       'Crime|Drama|Thriller', 'Action|Adventure|Comedy|Crime',
       'Drama|Mystery', 'Drama|Mystery|Romance', 'Thriller',
       'Adventure|Drama|IMAX', 'Action|Drama|Romance|War', 'Drama|Horror',
       'Adventure|Drama|War', 'Comedy|War', 'Crime|Drama|Mystery',
       'Action|Adventure|Mystery|Sci-Fi', 'Drama|Thriller|War',
       'Action|Romance|Western', 'Crime|Film-Noir|Mystery|Thriller',
       'Comedy|Crime|Drama', 'Action|Drama|Romance',
       'Adventure|Children|Drama', 'Action|Adventure|Crime|Thriller',
       'Action|Crime|Sci-Fi', 'Horror', 'Action|Children',
       'Comedy|Horror|Thriller', 'Fantasy|Horror|Mystery',
       'Comedy|Fantasy', 'Horror|Sci-Fi',
       'Action|Crime|Drama|Mystery|Sci-Fi|Thriller',
       'Drama|Musical|Romance', 'Drama|Fantasy',
       'Action|Adventure|Sci-Fi', 'Western',
       'Adventure|Comedy|Crime|Mystery', 'Adventure|Comedy',
       'Action|Comedy|Romance', 'Animation|Children|Comedy|Romance',
       'Drama|Musical', 'Children|Comedy|Fantasy', 'Comedy|Sci-Fi',
       'Adventure|Children|Comedy|Fantasy|Romance',
       'Drama|Fantasy|Romance', 'Drama|Romance|War|Western',
       'Drama|Horror|Sci-Fi', 'Action|Crime',
       'Action|Drama|Sci-Fi|Thriller', 'Comedy|Crime|Drama|Thriller',
       'Action|Thriller|Western', 'Horror|Thriller', 'Animation|Children',
       'Children|Drama|Fantasy|Mystery', 'Action|Drama|Thriller',
       'Comedy|Drama|Fantasy', 'Film-Noir|Thriller',
       'Action|Comedy|Sci-Fi', 'Adventure|Drama|Sci-Fi',
       'Action|Crime|Horror', 'Children', 'Drama|Film-Noir|Romance',
       'Drama|Mystery|Thriller', 'Action|Crime|Fantasy|Thriller',
       'Comedy|Drama|Romance|War', 'Action|Comedy',
       'Adventure|Children|Romance',
       'Adventure|Animation|Children|Drama|Musical|IMAX',
       'Drama|Horror|Mystery|Thriller', 'Action|Comedy|Crime|Fantasy',
       'Adventure|Comedy|Western', 'Action|Romance|Thriller',
       'Action|Adventure|Comedy|Romance|Thriller',
       'Drama|Horror|Romance|Thriller', 'Drama|Romance|War',
       'Action|Fantasy', 'Comedy|Thriller',
       'Action|Comedy|Crime|Thriller', 'Horror|Sci-Fi|Thriller',
       'Drama|Mystery|Romance|Thriller', 'Action|Comedy|Drama',
       'Drama|Western', 'Action|Adventure|Crime|Drama|Romance|Thriller',
       'Action|Comedy|War', 'Action|Adventure|Sci-Fi|Thriller',
       'Action|Adventure|Comedy|Fantasy', 'Comedy|Western',
       'Comedy|Mystery', 'Comedy|Drama|Romance|Thriller',
       'Action|Children|Romance', 'Action|Drama|Sci-Fi', 'Action|Drama',
       'Comedy|Mystery|Romance', 'Action|Drama|Mystery',
       'Action|Crime|Drama|Sci-Fi|Thriller', 'Crime|Thriller',
       'Comedy|Crime|Horror', 'Action|Adventure|Fantasy|Mystery',
       'Comedy|Romance|Thriller',
       'Action|Adventure|Children|Comedy|Fantasy|Sci-Fi',
       'Action|Mystery|Thriller', 'Animation|Children|Fantasy|Musical',
       'Action|Adventure|Comedy|Romance', 'Action|Drama|Western',
       'Action|Adventure|Animation|Children|Fantasy',
       'Comedy|Drama|Fantasy|Romance|Thriller',
       'Adventure|Animation|Children|Comedy|Musical', 'Action|Sci-Fi',
       'Adventure|Drama|Western', 'Crime|Horror|Thriller',
       'Animation|Children|Drama|Fantasy|Musical',
       'Animation|Children|Fantasy|Musical|Romance|IMAX',
       'Adventure|Western', 'Action|Comedy|Crime', 'Fantasy|Horror',
       'Action|Adventure|Animation|Horror|Sci-Fi', 'Action|Horror|Sci-Fi',
       'Crime|Drama|Mystery|Thriller',
       'Adventure|Animation|Children|Fantasy|Musical|Romance', 'Romance',
       'Action|Crime|Drama|War', 'Action|Adventure|Mystery|Thriller',
       'Adventure|Animation|Children|Fantasy|Musical', 'Comedy|Drama|War',
       'Adventure|Animation|Children|Comedy|Fantasy|Sci-Fi',
       'Adventure|Comedy|Sci-Fi', 'Drama|Mystery|Romance|Sci-Fi|Thriller',
       'Action|Adventure|Comedy|War', 'Action|Adventure',
       'Drama|Mystery|Western', 'Comedy|Fantasy|Sci-Fi',
       'Adventure|Animation|Comedy', 'Drama|Fantasy|Horror|Thriller',
       'Action|Adventure|Romance|Thriller', 'Animation|Sci-Fi',
       'Animation|Children|Comedy', 'Horror|Mystery',
       'Comedy|Fantasy|Romance|Sci-Fi', 'Action|Adventure|Drama|Thriller',
       'Comedy|Fantasy|Musical', 'Crime|Drama|Romance|Thriller',
       'Crime|Drama|Musical|Thriller', 'Sci-Fi|Thriller',
       'Children|Drama|Fantasy', 'Adventure|Animation|Children|Musical',
       'Adventure|Drama|Romance|War', 'Comedy|Musical|Romance',
       'Musical|Romance', 'Comedy|Musical',
       'Action|Adventure|Mystery|Romance|Thriller',
       'Comedy|Crime|Mystery|Romance|Thriller', 'Film-Noir|Mystery',
       'Comedy|Drama|Musical|Romance', 'Musical',
       'Adventure|Children|Fantasy|Musical',
       'Drama|Film-Noir|Mystery|Thriller', 'Film-Noir|Romance|Thriller',
       'Mystery|Romance|Thriller', 'Crime|Mystery|Romance|Thriller',
       'Adventure', 'Crime|Film-Noir|Mystery', 'Drama|Romance|Western',
       'Children|Drama|Fantasy|Romance', 'Adventure|Comedy|Romance|War',
       'Adventure|Comedy|Crime|Drama|Romance', 'Romance|War',
       'Crime|Film-Noir', 'Children|Comedy|Western',
       'Children|Comedy|Fantasy|Romance', 'Children|Comedy|Romance',
       'Children|Comedy|Drama', 'Children|Comedy|Mystery',
       'Animation|Children|Fantasy|Musical|Romance',
       'Animation|Children|Musical', 'Children|Comedy|Fantasy|Musical',
       'Animation|Children|Drama|Musical', 'Adventure|Children|Musical',
       'Animation|Children|Drama', 'Action|Horror|Sci-Fi|Thriller',
       'Documentary|Drama',
       'Animation|Children|Comedy|Fantasy|Musical|Romance',
       'Drama|Romance|Thriller', 'Children|Drama|Sci-Fi',
       'Action|Romance', 'Adventure|Comedy|Fantasy',
       'Animation|Children|Comedy|Crime',
       'Animation|Comedy|Drama|Fantasy', 'Crime|Drama|Film-Noir',
       'Documentary|Musical', 'Action|Adventure|Comedy|Fantasy|Romance',
       'Fantasy|Sci-Fi', 'Action|Adventure|Horror|Sci-Fi',
       'Action|Adventure|Western', 'Crime|Drama|Sci-Fi|Thriller',
       'Film-Noir|Mystery|Thriller',
       'Action|Adventure|Comedy|Fantasy|Horror',
       'Adventure|Drama|Romance', 'Crime|Horror', 'Action|Comedy|Musical',
       'Adventure|Animation|Children|Comedy|Sci-Fi',
       'Drama|Mystery|Sci-Fi', 'Comedy|Fantasy|Horror',
       'Crime|Drama|Film-Noir|Thriller', 'Crime|Film-Noir|Thriller',
       'Action|Crime|Romance|Thriller', 'Drama|Sci-Fi|Thriller',
       'Action|Adventure|Drama|Western', 'Comedy|Horror|Sci-Fi',
       'Comedy|Musical|War', 'Action|Comedy|Fantasy|Horror',
       'Action|Adventure|Drama|War',
       'Action|Drama|Mystery|Romance|Thriller', 'Comedy|Fantasy|Romance',
       'Crime|Thriller|War', 'Comedy|Mystery|Thriller',
       'Comedy|Drama|Film-Noir', 'Action|Adventure|Animation|Sci-Fi',
       'Action|Western', 'Fantasy|Horror|Romance|Thriller',
       'Drama|Fantasy|Horror', 'Horror|Mystery|Thriller',
       'Adventure|Children|Comedy', 'Adventure|Sci-Fi',
       'Action|Mystery|Sci-Fi', 'Action|Comedy|Western', 'Action|Horror',
       'Action|Comedy|Crime|Drama|Sci-Fi',
       'Adventure|Animation|Comedy|Crime',
       'Comedy|Horror|Mystery|Thriller', 'Action|Romance|War|Western',
       'Comedy|Drama|Fantasy|Romance', 'Action|Adventure|Comedy|Thriller',
       'Crime', 'Crime|Drama|Fantasy|Film-Noir|Mystery|Romance',
       'Action|Comedy|Crime|Drama', 'Action|Romance|Sci-Fi|Thriller',
       'Comedy|Drama|Mystery|Romance', 'Action|Adventure|Children',
       'Comedy|Crime|Romance', 'Action|Adventure|Comedy',
       'Action|Adventure|Comedy|Sci-Fi',
       'Action|Adventure|Fantasy|Thriller', 'Children|Fantasy',
       'Adventure|Romance', 'Action|Thriller|War',
       'Children|Comedy|Romance|Sci-Fi', 'Romance|Thriller',
       'Comedy|Drama|Sci-Fi',
       'Adventure|Animation|Children|Drama|Musical',
       'Action|Adventure|Drama|Sci-Fi', 'Action|Children|Comedy',
       'Adventure|Film-Noir|Sci-Fi|Thriller',
       'Crime|Drama|Fantasy|Thriller', 'Crime|Romance|Thriller',
       'Crime|Drama|Mystery|Romance|Thriller', 'Documentary|IMAX',
       'Comedy|Crime|Drama|Mystery|Thriller', 'Comedy|Documentary',
       'Adventure|Children|Comedy|Fantasy', 'Crime|Drama|Romance|War',
       'Adventure|Comedy|Drama', 'Adventure|Comedy|Romance',
       'Adventure|Animation|Children|Comedy|Drama|Musical|Romance',
       'Action|Crime|Mystery|Sci-Fi|Thriller',
       'Comedy|Crime|Drama|Romance|Thriller',
       'Animation|Children|Fantasy|War', 'Comedy|Drama|Musical',
       'Adventure|Fantasy|Musical',
       'Action|Adventure|Children|Comedy|Fantasy',
       'Drama|Mystery|Sci-Fi|Thriller', 'Adventure|Comedy|Sci-Fi|Western',
       'Children|Fantasy|Musical', 'Adventure|Animation|Children|Fantasy',
       'Children|Sci-Fi', 'Children|Comedy|Sci-Fi',
       'Action|Adventure|Children|Comedy', 'Adventure|Children|Sci-Fi',
       'Action|Animation|Children|Crime',
       'Children|Comedy|Fantasy|Horror',
       'Adventure|Children|Comedy|Fantasy|Sci-Fi',
       'Action|Crime|Drama|Mystery|Thriller', 'Film-Noir',
       'Drama|Fantasy|Mystery', 'Animation|Children|Comedy|Musical',
       'Animation|Children|Comedy|Musical|Romance',
       'Children|Comedy|Musical', 'Children|Musical',
       'Adventure|Comedy|Musical',
       'Adventure|Animation|Children|Crime|Drama',
       'Children|Drama|Fantasy|Mystery|Thriller',
       'Adventure|Children|Fantasy|Western',
       'Animation|Children|Comedy|Drama|Fantasy',
       'Action|Crime|Mystery|Thriller',
       'Adventure|Animation|Children|Drama|Fantasy',
       'Adventure|Animation|Children|Drama', 'Adventure|Fantasy',
       'Adventure|Animation|Children|Comedy',
       'Adventure|Animation|Children|Musical|Western',
       'Adventure|Fantasy|Romance', 'Adventure|Drama|Fantasy',
       'Action|Comedy|Drama|Horror', 'Action|Horror|Thriller',
       'Drama|Film-Noir|Thriller', 'Adventure|Drama|Mystery|Thriller',
       'Horror|Mystery|Sci-Fi|Thriller', 'Drama|Fantasy|Thriller',
       'Adventure|Drama|Fantasy|Romance', 'Sci-Fi',
       'Drama|Fantasy|Mystery|Romance', 'Action|Sci-Fi|War',
       'Fantasy|Horror|Thriller', 'Horror|Western',
       'Action|Adventure|Fantasy|Horror',
       'Adventure|Fantasy|Romance|Sci-Fi|Thriller',
       'Comedy|Crime|Mystery', 'Action|Drama|Romance|Sci-Fi',
       'Animation|Musical', 'Action|Adventure|Thriller|War',
       'Comedy|Crime|Mystery|Thriller',
       'Action|Adventure|Children|Fantasy|Mystery|Thriller',
       'Action|Adventure|Children|Drama',
       'Action|Adventure|Drama|Fantasy|Thriller', 'Horror|Mystery|Sci-Fi',
       'Drama|Horror|Sci-Fi|Thriller', 'Action|Comedy|Romance|Thriller',
       'Action|War', 'Adventure|Comedy|Thriller',
       'Action|Sci-Fi|Thriller|Western', 'Drama|Romance|Sci-Fi|Thriller',
       'Drama|Film-Noir',
       'Action|Adventure|Comedy|Fantasy|Horror|Thriller',
       'Action|Adventure|Crime|Sci-Fi|Thriller',
       'Adventure|Drama|Mystery', 'Horror|Romance',
       'Comedy|Horror|Musical|Sci-Fi', 'War', 'Comedy|Romance|Sci-Fi',
       'Animation|Comedy|Musical', 'Action|Comedy|Sci-Fi|Western',
       'Action|Comedy|Fantasy', 'Adventure|Drama|Thriller',
       'Action|Adventure|Comedy|Fantasy|Mystery', 'Comedy|Horror|Musical',
       'Adventure|Animation|Children|Drama|Sci-Fi',
       'Drama|Horror|Mystery', 'Action|Mystery',
       'Comedy|Horror|Romance|Thriller', 'Action|Drama|Romance|Thriller',
       'Animation|Horror|Mystery|Thriller',
       'Adventure|Children|Comedy|Drama', 'Adventure|Sci-Fi|Thriller',
       'Adventure|Animation|Comedy|Fantasy|Musical',
       'Animation|Children|Fantasy', 'Action|Adventure|Comedy|Drama|War',
       'Crime|Drama|Western', 'Comedy|Crime|Drama|Fantasy',
       'Drama|Film-Noir|Mystery|Romance', 'Musical|Romance|War',
       'Adventure|Comedy|Fantasy|Sci-Fi', 'Drama|Fantasy|Musical',
       'Action|Crime|Sci-Fi|Thriller',
       'Adventure|Animation|Children|Comedy|Crime|Fantasy|Mystery',
       'Action|Adventure|Animation|Drama|Fantasy',
       'Adventure|Animation|Children|Fantasy|Sci-Fi',
       'Fantasy|Horror|Mystery|Romance',
       'Action|Fantasy|Horror|Mystery|Thriller', 'Drama|Romance|Sci-Fi',
       'Animation|Children|Musical|IMAX', 'Action|Comedy|Horror',
       'Action|Crime|Thriller|Western', 'Fantasy|Horror|Mystery|Thriller',
       'Romance|Western', 'Adventure|Crime|Drama|Romance',
       'Adventure|Crime|Drama', 'Animation|Comedy',
       'Action|Children|Comedy|Fantasy|Sci-Fi', 'Action|Children|Fantasy',
       'Action|Adventure|Drama|Thriller|Western',
       'Crime|Horror|Mystery|Thriller', 'Action|Adventure|Comedy|Western',
       'Action|Drama|Thriller|Western',
       'Adventure|Animation|Fantasy|Sci-Fi',
       'Comedy|Horror|Sci-Fi|Thriller', 'Adventure|Drama|Romance|Sci-Fi',
       'Film-Noir|Horror|Mystery|Thriller',
       'Action|Adventure|Animation|Children|Sci-Fi',
       'Action|Fantasy|Horror|Sci-Fi|Thriller',
       'Action|Comedy|Crime|Romance', 'Adventure|Horror|Sci-Fi',
       'Adventure|Animation|Children|Sci-Fi', 'Adventure|Comedy|Crime',
       'Action|Drama|War|Western',
       'Action|Crime|Mystery|Romance|Thriller', 'Romance|Sci-Fi',
       'Fantasy|Romance', 'Action|Adventure|Fantasy|Sci-Fi',
       'Adventure|Comedy|Horror', 'Animation|Comedy|Fantasy',
       'Action|Adventure|War', 'Action|Crime|Drama|Horror|Thriller',
       'Crime|Mystery', 'Adventure|Comedy|Mystery|Romance',
       'Adventure|Animation|Children|Comedy|Fantasy|Romance',
       'Adventure|War|Western', 'Comedy|Drama|Mystery|Thriller',
       'Comedy|Drama|Romance|Western', 'Action|Comedy|Sci-Fi|Thriller',
       'Adventure|Documentary|IMAX', 'Animation|Drama|Sci-Fi|IMAX',
       'Action|Comedy|Horror|Sci-Fi', 'Comedy|Musical|Sci-Fi',
       'Drama|Musical|Mystery', 'Crime|Musical', 'Comedy|Musical|Western',
       'Action|Animation|Comedy|Crime|Drama|Romance|Thriller',
       'Action|Adventure|Drama|Romance',
       'Comedy|Fantasy|Horror|Musical|Thriller', 'Crime|Horror|Mystery',
       'Action|Adventure|Drama|Romance|Thriller',
       'Action|Comedy|Romance|War', 'Action|Adventure|Comedy|Drama',
       'Adventure|Thriller', 'Crime|Drama|Film-Noir|Mystery|Thriller',
       'Action|Animation|Sci-Fi', 'Animation|Drama|Fantasy',
       'Drama|Fantasy|Mystery|Sci-Fi',
       'Drama|Fantasy|Horror|Thriller|War', 'Fantasy|Mystery|Thriller',
       'Action|Adventure|Comedy|Drama|Romance|Thriller',
       'Mystery|Romance|Sci-Fi|Thriller',
       'Adventure|Crime|Drama|Thriller', 'Comedy|Drama|Mystery',
       'Animation|Fantasy', 'Drama|Fantasy|Horror|Mystery|Thriller',
       'Drama|Fantasy|Mystery|Romance|Thriller',
       'Animation|Fantasy|Horror|Sci-Fi', 'Documentary|War',
       'Children|Horror|Mystery|Thriller', 'Musical|Western',
       'Action|Adventure|Sci-Fi|IMAX',
       'Adventure|Animation|Children|Western',
       'Adventure|Children|Comedy|Fantasy|Mystery',
       'Adventure|Drama|Horror|Mystery|Thriller',
       'Comedy|Sci-Fi|Thriller', 'Action|Animation|Children|Comedy',
       'Children|Drama|Musical', 'Comedy|Drama|Fantasy|Sci-Fi',
       'Action|Adventure|Fantasy|Romance',
       'Comedy|Crime|Romance|Thriller', 'Adventure|War',
       'Comedy|Crime|Musical|Mystery', 'Adventure|Animation|Fantasy',
       'Animation|Comedy|War', 'Action|Adventure|Comedy|Crime|Drama',
       'Animation|Drama|War', 'Documentary|Horror',
       'Action|Horror|Mystery|Sci-Fi', 'Action|Comedy|Documentary',
       'Adventure|Animation|Children|Sci-Fi|IMAX', 'Comedy|Drama|Horror',
       'Animation|Children|Drama|Fantasy', 'Comedy|Crime|Drama|Musical',
       'Action|Adventure|Animation|Fantasy|Sci-Fi',
       'Action|Adventure|Crime|Drama|Thriller',
       'Comedy|Crime|Drama|Romance', 'Comedy|Documentary|Musical',
       'Action|Animation|Sci-Fi|Thriller',
       'Adventure|Children|Comedy|Mystery', 'Mystery|Sci-Fi',
       'Adventure|Children|Comedy|Fantasy|Musical',
       'Action|Adventure|Animation|Children|Fantasy|Sci-Fi',
       'Action|Adventure|Sci-Fi|Thriller|IMAX',
       'Action|Drama|Horror|Sci-Fi|Thriller', 'Drama|War|Western',
       'Comedy|Crime|Mystery|Romance', 'Comedy|War|Western',
       'Action|Adventure|Comedy|Crime|Thriller', 'Action|Fantasy|Sci-Fi',
       'Action|Comedy|Thriller', 'Comedy|Crime|Drama|War',
       'Adventure|Comedy|Crime|Thriller',
       'Action|Adventure|Children|Fantasy',
       'Drama|Fantasy|Musical|Romance', 'Animation|Drama|Romance',
       'Comedy|Romance|Sci-Fi|Thriller', 'Action|Fantasy|Horror',
       'Fantasy|Horror|Sci-Fi|Thriller', 'Comedy|Musical|Romance|Western',
       'Drama|Fantasy|Sci-Fi', 'Children|Comedy|Crime|Musical',
       'Action|Adventure|Animation|Fantasy', 'Crime|Documentary',
       'Adventure|Comedy|Drama|Fantasy|Mystery|Sci-Fi|Thriller',
       'Action|Animation|Children|Fantasy', 'Comedy|Mystery|Sci-Fi',
       'Adventure|Thriller|Western', 'Comedy|Crime|Drama|Mystery|Romance',
       'Action|Crime|Fantasy|Sci-Fi|Thriller', 'Crime|Fantasy|Horror',
       'Action|Drama|Horror|Thriller', 'Comedy|Fantasy|Horror|Thriller',
       'Action|Drama|Romance|Western',
       'Adventure|Animation|Drama|Fantasy|Sci-Fi',
       'Animation|Drama|Sci-Fi|War', 'Action|Adventure|Drama|Fantasy',
       'Adventure|Drama|Romance|Thriller|War',
       'Crime|Drama|Film-Noir|Romance|Thriller',
       'Drama|Film-Noir|Mystery',
       'Action|Comedy|Crime|Drama|Horror|Thriller',
       'Adventure|Documentary', 'Action|Adventure|Children|Comedy|Crime',
       'Animation|Comedy|Fantasy|Musical',
       'Action|Adventure|Children|Comedy|Mystery', 'Action|Drama|Horror',
       'Musical|Romance|Western', 'Action|Drama|Thriller|War',
       'Comedy|Crime|Drama|Musical|Mystery|Romance',
       'Adventure|Comedy|War', 'Fantasy|Musical|Romance',
       'Drama|Thriller|Western', 'Crime|Horror|Sci-Fi',
       'Animation|Fantasy|Thriller', 'Children|Comedy|Fantasy|Sci-Fi',
       'Mystery', 'Action|Adventure|Animation|Comedy|Crime|Mystery',
       'Adventure|Animation|Children|Comedy|Musical|Romance',
       'Action|Adventure|Drama|Sci-Fi|Thriller', 'Adventure|Fantasy|IMAX',
       'Action|Crime|Horror|Mystery|Thriller', 'Comedy|Fantasy|Thriller',
       'Animation|Comedy|Drama|Fantasy|Sci-Fi',
       'Comedy|Documentary|Drama', 'Crime|Drama|Film-Noir|Romance',
       'Action|Adventure|Drama|Romance|Thriller|Western',
       'Crime|Drama|Horror', 'Adventure|Comedy|Fantasy|Musical',
       'Adventure|Animation|Drama', 'Comedy|Drama|Fantasy|Mystery',
       'Action|Crime|Fantasy', 'Comedy|Drama|Sci-Fi|War',
       'Adventure|Fantasy|Sci-Fi',
       'Adventure|Drama|Horror|Sci-Fi|Thriller',
       'Action|Adventure|Animation|Comedy',

In [16]:
# Đếm có bao nhiêu phim không được gán nhãn, được gán giá trị (no genres listed)
count = len(
    movies_df[movies_df["genres"] == "(no genres listed)"]
)
print(count)

34

In [17]:
# Thay (no genres listed) thành ""
movies_df["genres"] = movies_df["genres"].replace(
    "(no genres listed)",
    ""
)

In [18]:
# Kiểm tra lại đã thay chưa
count = len(
    movies_df[movies_df["genres"] == "(no genres listed)"]
)
print(count)

0

In [19]:
# Thay dấu | trong genres bằng khoảng trắng
movies_df["genres"] = movies_df["genres"].str.replace(
    "|",
    " ",
    regex=False
)
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0
1,2,Jumanji,Adventure Children Fantasy,1995.0
2,3,Grumpier Old Men,Comedy Romance,1995.0
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0
4,5,Father of the Bride Part II,Comedy,1995.0

In [20]:
# Xử lý tags
# Chuẩn hóa thành chữ thường 
tags_df["tag"] = tags_df["tag"].str.lower()
tags_df.head()

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     boxing story  1445715207
4       2    89774              mma  1445715200

In [21]:
# Loại bỏ khoảng trắng thừa, ở 2 đầu nếu người dùng lỡ bấm space trước/sau khi viết 
tags_df["tag"] = tags_df["tag"].str.strip()
tags_df.head()

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     boxing story  1445715207
4       2    89774              mma  1445715200

In [22]:
# Gom tag theo movie
movie_tags = tags_df.groupby("movieId")["tag"].apply(" ".join).reset_index()
movie_tags.head()

   movieId                                           tag
0        1                               pixar pixar fun
1        2  fantasy magic board game robin williams game
2        3                                     moldy old
3        5                              pregnancy remake
4        7                                        remake

In [23]:
# Ghép tag vào movies
movies_nlp = movies_df.merge(
    movie_tags,
    on="movieId",
    how="left"
)
movies_nlp.head()

,movieId,title,genres,year,tag
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar pixar fun
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams game
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,NaN
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake

In [24]:
# Xử lý Null
movies_nlp["tag"] = (
    movies_nlp["tag"]
    .fillna("")
)
movies_nlp.head()

,movieId,title,genres,year,tag
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar pixar fun
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams game
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake

In [25]:
# Ghép title, genres, tag thành 1 cột content 
movies_nlp["content"] = (
    movies_nlp["title"]
    + " "
    + movies_nlp["genres"]
    + " "
    + movies_nlp["tag"]
)
movies_nlp.head()

,movieId,title,genres,year,tag,content
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar pixar fun,Toy Story Adventure Animation Children Comedy ...
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams game,Jumanji Adventure Children Fantasy fantasy mag...
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old,Grumpier Old Men Comedy Romance moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,,Waiting to Exhale Comedy Drama Romance
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake,Father of the Bride Part II Comedy pregnancy r...

In [26]:
# Chuyển về chữ thường 
movies_nlp["content"] = (
    movies_nlp["content"]
    .str.lower()
)
movies_nlp.head()

,movieId,title,genres,year,tag,content
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar pixar fun,toy story adventure animation children comedy ...
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams game,jumanji adventure children fantasy fantasy mag...
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old,grumpier old men comedy romance moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,,waiting to exhale comedy drama romance
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake,father of the bride part ii comedy pregnancy r...

In [27]:
# Đếm số ký tự đặc biệt trong content 
special_content = movies_nlp[
    movies_nlp["content"].str.contains(
        r"[^a-zA-Z0-9\s]",
        regex=True,
        na=False
    )
]

print(len(special_content))

4858

In [28]:
# Loại bỏ ký tự đặc biệt, chỉ giữ lại chữ cái, số và khoảng trắng
movies_nlp["content"] = (
    movies_nlp["content"]
    .str.replace(
        r"[^a-zA-Z0-9\s]",
        " ",
        regex=True
    )
)
movies_nlp.head()

,movieId,title,genres,year,tag,content
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar pixar fun,toy story adventure animation children comedy ...
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams game,jumanji adventure children fantasy fantasy mag...
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old,grumpier old men comedy romance moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,,waiting to exhale comedy drama romance
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake,father of the bride part ii comedy pregnancy r...

In [29]:
# Loại bỏ khoảng trắng thừa, ở giữa nếu có nhiều khoảng trắng sẽ thành 1 khoảng trắng, ở 2 đầu nếu có sẽ bị xóa
movies_nlp["content"] = (
    movies_nlp["content"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)
movies_nlp.head()

,movieId,title,genres,year,tag,content
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,1995.0,pixar pixar fun,toy story adventure animation children comedy ...
1,2,Jumanji,Adventure Children Fantasy,1995.0,fantasy magic board game robin williams game,jumanji adventure children fantasy fantasy mag...
2,3,Grumpier Old Men,Comedy Romance,1995.0,moldy old,grumpier old men comedy romance moldy old
3,4,Waiting to Exhale,Comedy Drama Romance,1995.0,,waiting to exhale comedy drama romance
4,5,Father of the Bride Part II,Comedy,1995.0,pregnancy remake,father of the bride part ii comedy pregnancy r...

In [30]:
# Tính TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(
    stop_words="english"
)
tfidf_matrix = tfidf.fit_transform(
    movies_nlp["content"]
)
print(tfidf_matrix.shape)

(9742, 9801)

In [31]:
feature_names = tfidf.get_feature_names_out()

print(feature_names[:200])

['00' '000' '007' '01' '04' '06' '09' '10' '100' '1000' '101' '102' '10th'
 '11' '1138' '11th' '12' '120' '127' '13' '13th' '14' '1408' '1492' '15'
 '16' '1600' '17' '174' '1776' '18' '187' '19' '1900' '1900s' '1920s'
 '1933' '1935' '1941' '1950s' '1960s' '1969' '1970s' '1972' '1975' '1980s'
 '1984' '1985' '1990' '1990s' '1992' '1st' '20' '200' '2000' '2001' '2006'
 '2007' '2010' '2012' '2018' '2046' '2048' '2049' '21' '211' '22' '23'
 '24' '25' '250' '25th' '27' '28' '281' '2d' '2nd' '30' '300' '3000' '31'
 '33' '34th' '35' '37th' '39' '3d' '3dd' '40' '400' '42' '42nd' '43' '44'
 '45' '451' '46' '47' '48' '49' '4th' '50' '500' '51' '52' '54' '57' '571'
 '5th' '60' '61' '66' '6th' '70' '70mm' '71' '73' '77' '777' '7th' '80'
 '800' '81' '84' '8mm' '8th' '90' '900' '911' '93' '96' '964' '99' '9to5'
 'aan' 'aardman' 'aaron' 'abandoned' 'abbey' 'abbott' 'abbotts' 'abcs'
 'abduction' 'abiding' 'abominable' 'abortion' 'abracadabra' 'abraham'
 'abre' 'abroad' 'absence' 'absent' 'absentia' 'absolute' 'absolutely'
 'absorbing' 'abstract' 'abuse' 'abyss' 'academy' 'accepted' 'accident'
 'accidental' 'accidents' 'according' 'accountant' 'accused' 'ace' 'aces'
 'achronological' 'acid' 'acquaintance' 'acres' 'act' 'acting' 'action'
 'activity' 'actors' 'actress' 'actrice' 'acts' 'actually' 'ad' 'adam'
 'adams' 'adanggaman' 'adaptation' 'addams' 'addendum' 'adderall' 'addict'
 'addicted' 'addiction' 'adentro' 'adjustment' 'admirer' 'admission' 'ado'
 'adolescence' 'adoption']

In [32]:
# Tính cosine similarity để đo độ tương đồng giữa các vector phim.
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(
    tfidf_matrix,
    tfidf_matrix
)
print(cosine_sim.shape)

(9742, 9742)

In [33]:
# Tạo Series để map index với title, dùng drop_duplicates để tránh trường hợp có phim trùng tên
indices = pd.Series(
    movies_nlp.index,
    index=movies_nlp["title"]
).drop_duplicates()
indices.head()

title
Toy Story                      0
Jumanji                        1
Grumpier Old Men               2
Waiting to Exhale              3
Father of the Bride Part II    4
dtype: int64

In [34]:
# Hàm đề xuất phim dựa trên title, trả về 10 phim tương tự nhất
def recommend_movies(title, cosine_sim=cosine_sim): 
    idx = indices[title]
    sim_scores = list(
        enumerate(cosine_sim[idx])
    )
    sim_scores = sorted(
        sim_scores,
        key=lambda x: x[1],
        reverse=True
    )
    sim_scores = sim_scores[1:11]

    movie_indices = [
        i[0] for i in sim_scores
    ]
    return movies_nlp[
        ["title","genres"]
    ].iloc[movie_indices]

In [35]:
# Test hàm đề xuất
recommend_movies("Toy Story")

,title,genres
2355,Toy Story 2,Adventure Animation Children Comedy Fantasy
1757,"Bug's Life, A",Adventure Animation Children Comedy
7355,Toy Story 3,Adventure Animation Children Comedy Fantasy IMAX
3595,"Toy, The",Comedy
3733,Fun,Crime Drama
7039,Up,Adventure Animation Children Drama
2539,We're Back! A Dinosaur's Story,Adventure Animation Children Fantasy
4089,Toy Soldiers,Action Drama
2227,"Story of Us, The",Comedy Drama
1617,"NeverEnding Story, The",Adventure Children Fantasy

In [36]:
!pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit_surprise-1.1.5-cp312-cp312-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: joblib>=1.4.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from scikit-surprise) (1.5.1)
Requirement already satisfied: numpy>=1.24.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from scikit-surprise) (2.2.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from scikit-surprise) (1.16.1)
Downloading scikit_surprise-1.1.5-cp312-cp312-win_amd64.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ---------------------------------------- 1.3/1.3 MB 6.8 MB/s eta 0:00:00
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.5

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [37]:
# =====================================================================
# NHÁNH 2: TRÍCH CHỌN ĐẶC TRƯNG ẨN SVD (HÀNH VI NGƯỜI DÙNG)
# =====================================================================

from surprise import Dataset, Reader, SVD
from surprise.model_selection import train_test_split


# 1. Định dạng cấu trúc dữ liệu tương tác cho thư viện Surprise từ bảng ratings_svd ở Cell 6
reader = Reader(rating_scale=(0.5, 5.0))
data_surprise = Dataset.load_from_df(ratings_svd, reader)


# 2. Chia dữ liệu thành 80% Train (huấn luyện) và 20% Test (kiểm thử)
trainset, testset = train_test_split(data_surprise, test_size=0.20, random_state=42)


# 3. Khởi tạo thuật toán Funk SVD và tiến hành huấn luyện (fit) để học các đặc trưng ẩn
svd_model = SVD(n_factors=100, random_state=42)
svd_model.fit(trainset)


print("--- KẾT QUẢ TRÍCH CHỌN ĐẶC TRƯNG SVD ---")
# 4. Xuất kích thước và xem thử ma trận đặc trưng ẩn của Người dùng (P)
user_features = svd_model.pu
print(f"Kích thước ma trận đặc trưng ẩn Người dùng (P): {user_features.shape}")
print(f"Vector đặc trưng ẩn của User đầu tiên (10 chiều đầu): \n{user_features[0][:10]}\n")


# 5. Xuất kích thước và xem thử ma trận đặc trưng ẩn của Bộ phim (Q)
movie_features = svd_model.qi
print(f"Kích thước ma trận đặc trưng ẩn Bộ phim (Q): {movie_features.shape}")
print(f"Vector đặc trưng ẩn của Movie đầu tiên (10 chiều đầu): \n{movie_features[0][:10]}")

--- KẾT QUẢ TRÍCH CHỌN ĐẶC TRƯNG SVD ---
Kích thước ma trận đặc trưng ẩn Người dùng (P): (610, 100)
Vector đặc trưng ẩn của User đầu tiên (10 chiều đầu):
[ 0.18456538 -0.01395499 -0.11249967  0.01019481  0.04821811 -0.00102196
  0.10881286  0.15684443 -0.1052382  -0.14101497]

Kích thước ma trận đặc trưng ẩn Bộ phim (Q): (8928, 100)
Vector đặc trưng ẩn của Movie đầu tiên (10 chiều đầu):
[-0.11398582 -0.04625663  0.0084922  -0.00074861  0.07695524 -0.0119714
  0.19301745  0.0512917   0.00971207 -0.17198096]

Ý tưởng chính:

SVD dự đoán user có thể chấm một phim bao nhiêu điểm.
TF-IDF biểu diễn nội dung phim bằng vector số.
User Profile được tạo từ các phim user đã đánh giá cao.
HybridScore kết hợp điểm SVD và điểm nội dung để xếp hạng phim chưa xem.

In [ ]:
# Kiểm tra lại các biến quan trọng đã có từ phần trên
required_variables = [
    "ratings_svd",
    "movies_nlp",
    "tfidf_matrix",
    "svd_model",
    "testset"
]

for var_name in required_variables:
    if var_name not in globals():
        raise NameError(f"Bạn cần chạy các cell phía trên trước. Biến còn thiếu: {var_name}")

print("Các biến cần thiết đã sẵn sàng.")
print("ratings_svd:", ratings_svd.shape)
print("movies_nlp:", movies_nlp.shape)
print("tfidf_matrix:", tfidf_matrix.shape)

Đánh giá mô hình SVD đã huấn luyện
Ở cell trước, mô hình SVD đã được huấn luyện bằng lệnh svd_model.fit(trainset). Bước này dùng tập testset đã tách ở trên để kiểm tra mô hình dự đoán rating tốt hay chưa.

Hai chỉ số thường dùng:

RMSE: sai số căn bậc hai trung bình, phạt mạnh các lỗi lớn.
MAE: sai số tuyệt đối trung bình.
Hai chỉ số này càng thấp thì mô hình dự đoán rating càng tốt.

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
import pandas as pd


def evaluate_svd_model(model, testset):
    y_true = []
    y_pred = []

    for user_id, movie_id, true_rating in testset:
        predicted_rating = model.predict(user_id, movie_id).est

        y_true.append(true_rating)
        y_pred.append(predicted_rating)

    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)

    return rmse, mae


svd_rmse, svd_mae = evaluate_svd_model(svd_model, testset)

print("SVD RMSE:", svd_rmse)
print("SVD MAE:", svd_mae)

Xem user thích những thể loại nào
Bước này chưa phải gợi ý phim, mà dùng để giải thích hệ thống hiểu sở thích người dùng như thế nào.

Cách làm:

Lấy các phim mà user đã đánh giá cao, ví dụ rating từ 3.5 trở lên.
Ghép với bảng phim để lấy genres.
Đếm thể loại nào xuất hiện nhiều và có rating trung bình cao.
Kết quả giúp giải thích rằng hệ thống không cần người dùng nhập tên phim, mà tự học gu từ lịch sử rating.

In [ ]:
def get_user_favorite_genres(user_id, ratings_df, movies_df, min_rating=3.5):
    user_ratings = ratings_df[
        (ratings_df["userId"] == user_id) &
        (ratings_df["rating"] >= min_rating)
    ].copy()

    if user_ratings.empty:
        return pd.DataFrame(columns=["genre", "count", "avg_rating"])

    user_movies = user_ratings.merge(
        movies_df[["movieId", "genres"]],
        on="movieId",
        how="left"
    )

    genre_stats = {}

    for row in user_movies.itertuples():
        genres_text = str(row.genres).replace("|", " ")
        genres = genres_text.split()

        for genre in genres:
            if genre not in genre_stats:
                genre_stats[genre] = {
                    "total_rating": 0,
                    "count": 0
                }

            genre_stats[genre]["total_rating"] += row.rating
            genre_stats[genre]["count"] += 1

    result = []

    for genre, stats in genre_stats.items():
        result.append({
            "genre": genre,
            "count": stats["count"],
            "avg_rating": stats["total_rating"] / stats["count"]
        })

    return (
        pd.DataFrame(result)
        .sort_values(by=["avg_rating", "count"], ascending=False)
        .reset_index(drop=True)
    )


# Ví dụ: xem gu thể loại của user 1
get_user_favorite_genres(
    user_id=1,
    ratings_df=ratings_svd,
    movies_df=movies_nlp,
    min_rating=3.5
).head(10)

Tạo ánh xạ từ movieId sang vị trí trong ma trận TF-IDF
Trong bảng rating, mỗi phim được nhận diện bằng movieId.

Nhưng trong tfidf_matrix, mỗi phim được nhận diện bằng index dòng: 0, 1, 2, ...

Vì vậy cần tạo bảng tra cứu:

movieId → index trong tfidf_matrix

In [ ]:
movie_id_to_index = pd.Series(
    movies_nlp.index,
    index=movies_nlp["movieId"]
).to_dict()

print("Số movieId map được:", len(movie_id_to_index))

Xây dựng hồ sơ sở thích người dùng bằng TF-IDF
Đây là bước quan trọng của phần Content-based cá nhân hóa.

Thay vì nhập một tên phim rồi tìm phim tương tự, ta làm như sau:

Lấy các phim user đã rating cao.
Lấy vector TF-IDF của các phim đó.
Tính trung bình có trọng số theo rating.
Phim user chấm 5 sao sẽ ảnh hưởng mạnh hơn phim user chấm 3.5 sao.

Kết quả là một vector gọi là user_profile, biểu diễn gu nội dung của user.

In [ ]:
from scipy.sparse import vstack


def build_user_profile(user_id, ratings_df, min_rating=3.5):
    user_ratings = ratings_df[
        (ratings_df["userId"] == user_id) &
        (ratings_df["rating"] >= min_rating)
    ].copy()

    if user_ratings.empty:
        return None

    movie_vectors = []
    weights = []

    for row in user_ratings.itertuples():
        movie_id = row.movieId

        if movie_id in movie_id_to_index:
            movie_index = movie_id_to_index[movie_id]
            movie_vectors.append(tfidf_matrix[movie_index])
            weights.append(row.rating)

    if len(movie_vectors) == 0:
        return None

    movie_matrix = vstack(movie_vectors)
    weights = np.array(weights)

    # Nhân mỗi vector phim với rating tương ứng, sau đó lấy trung bình có trọng số
    user_profile = movie_matrix.multiply(weights[:, None]).sum(axis=0) / weights.sum()

    return np.asarray(user_profile)


user_profile_demo = build_user_profile(
    user_id=1,
    ratings_df=ratings_svd,
    min_rating=3.5
)

print("Kích thước user profile:", user_profile_demo.shape)

Tính ContentScore cho từng phim
ContentScore trả lời câu hỏi:

Phim này có giống gu nội dung của user không?

Cách tính:

So sánh vector user_profile với vector TF-IDF của toàn bộ phim.
Dùng Cosine Similarity để lấy điểm từ 0 đến 1.
Điểm càng cao thì phim càng giống sở thích nội dung của user.

In [ ]:
def get_user_content_scores(user_id, ratings_df, min_rating=3.5):
    user_profile = build_user_profile(
        user_id=user_id,
        ratings_df=ratings_df,
        min_rating=min_rating
    )

    if user_profile is None:
        return None

    content_scores = cosine_similarity(
        user_profile,
        tfidf_matrix
    ).flatten()

    return content_scores


content_scores_demo = get_user_content_scores(
    user_id=1,
    ratings_df=ratings_svd,
    min_rating=3.5
)

print("Số điểm ContentScore của user 1:", len(content_scores_demo))
print("5 điểm đầu:", content_scores_demo[:5])

Tạo hàm gợi ý phim Hybrid theo userId
Bây giờ kết hợp hai nguồn điểm:

SVDScore: điểm rating mà SVD dự đoán user sẽ chấm cho phim.
ContentScore: điểm phim đó giống gu nội dung của user.
Vì SVD dự đoán rating trong khoảng 0.5 đến 5.0, còn ContentScore nằm trong khoảng 0 đến 1, ta chuẩn hóa điểm SVD về 0 đến 1.

Công thức:

HybridScore = alpha * SVDScore_norm + (1 - alpha) * ContentScore

Với alpha = 0.7, hệ thống ưu tiên 70% hành vi rating và 30% nội dung phim.

In [ ]:
def normalize_svd_score(score, min_rating=0.5, max_rating=5.0):
    return (score - min_rating) / (max_rating - min_rating)


def recommend_movies_for_user(user_id, top_n=10, alpha=0.7, min_rating_for_profile=3.5):
    content_scores = get_user_content_scores(
        user_id=user_id,
        ratings_df=ratings_svd,
        min_rating=min_rating_for_profile
    )

    if content_scores is None:
        return pd.DataFrame({
            "message": [f"User {user_id} chưa có đủ phim rating cao để tạo hồ sơ sở thích."]
        })

    watched_movie_ids = set(
        ratings_svd[ratings_svd["userId"] == user_id]["movieId"]
    )

    recommendations = []

    for movie_index, movie in movies_nlp.iterrows():
        movie_id = movie["movieId"]

        # Không gợi ý lại phim user đã xem/rating
        if movie_id in watched_movie_ids:
            continue

        svd_pred_rating = svd_model.predict(user_id, movie_id).est
        svd_score_norm = normalize_svd_score(svd_pred_rating)
        content_score = content_scores[movie_index]

        hybrid_score = alpha * svd_score_norm + (1 - alpha) * content_score

        recommendations.append({
            "movieId": movie_id,
            "title": movie["title"],
            "genres": movie["genres"],
            "svd_pred_rating": svd_pred_rating,
            "content_score": content_score,
            "hybrid_score": hybrid_score
        })

    recommendations_df = pd.DataFrame(recommendations)

    return (
        recommendations_df
        .sort_values(by="hybrid_score", ascending=False)
        .head(top_n)
        .reset_index(drop=True)
    )

Chạy thử hệ thống gợi ý cá nhân hóa
Ở bước này chỉ cần nhập userId.

Hệ thống sẽ:

Hiển thị các thể loại user có xu hướng thích.
Gợi ý top phim user chưa xem dựa trên HybridScore.

In [ ]:
demo_user_id = 1

print("Các thể loại user có xu hướng thích:")
display(
    get_user_favorite_genres(
        user_id=demo_user_id,
        ratings_df=ratings_svd,
        movies_df=movies_nlp,
        min_rating=3.5
    ).head(10)
)

print("Top phim gợi ý theo Hybrid:")
display(
    recommend_movies_for_user(
        user_id=demo_user_id,
        top_n=10,
        alpha=0.7,
        min_rating_for_profile=3.5
    )
)

Thử nhiều giá trị alpha
Bước này giúp giải thích phần hyper-parameter của mô hình Hybrid.

alpha càng lớn: hệ thống dựa nhiều hơn vào SVD.
alpha càng nhỏ: hệ thống dựa nhiều hơn vào nội dung phim.
Cell này không dùng để đánh giá RMSE trực tiếp, mà dùng để quan sát danh sách gợi ý thay đổi như thế nào khi thay đổi trọng số Hybrid.

In [ ]:
for alpha in [0.5, 0.7, 0.9]:
    print(f"
Top 5 phim gợi ý cho user {demo_user_id} với alpha = {alpha}")
    display(
        recommend_movies_for_user(
            user_id=demo_user_id,
            top_n=5,
            alpha=alpha,
            min_rating_for_profile=3.5
        )[["title", "genres", "svd_pred_rating", "content_score", "hybrid_score"]]
    )